import re
import json
from ast_nodes import ComponentNode

class AstroCodeGenerator:
    def __init__(self, component_ast: ComponentNode):
        self.ast = component_ast

    def generate_js(self) -> str:
        ast = self.ast
        
        # 1. Imports
        imports_code = "import React, { useState, useEffect } from 'react';\n"
        for lib, items in ast.imports.items():
            imports_code += f"import {{ {', '.join(items)} }} from '{lib}';\n"

        # 2. State definition
        state_code = ""
        for state in ast.states:
            val = json.dumps(state.initial_value)
            state_code += f"  const [{state.name}, set_{state.name}] = React.useState({val});\n"

        # 3. Reactive methods mapping
        methods_code = ""
        for method in ast.methods:
            body = method.body
            for state in ast.states:
                body = re.sub(
                    rf"state\.{state.name}\s*\+=\s*(.+)",
                    f"set_{state.name}(prev => prev + \\1)",
                    body
                )
                body = re.sub(
                    rf"state\.{state.name}\s*=\s*(.+)",
                    f"set_{state.name}(\\1)",
                    body
                )
                body = re.sub(
                    rf"state\.{state.name}\.push\((.+)\)",
                    f"set_{state.name}(prev => [...prev, \\1])",
                    body
                )
            methods_code += f"  const {method.name} = () => {{\n    {body};\n  }};\n\n"

        # 4. Lifecycle hooks (useEffect)
        effects_code = ""
        for effect in ast.effects:
            deps = ", ".join(effect.dependencies)
            effects_code += f"  React.useEffect(() => {{\n    {effect.body};\n  }}, [{deps}]);\n\n"

        # 5. Inline CSS Styles
        styles_code = ""
        if ast.styles:
            styles_code = f"  const styles = {json.dumps(ast.styles, indent=4)};\n\n"

        # 6. Scope mapping in JSX
        jsx = ast.render_tree or "<div></div>"
        for state in ast.states:
            jsx = jsx.replace(f"state.{state.name}", state.name)
        for prop_key in ast.props.keys():
            jsx = jsx.replace(f"props.{prop_key}", f"props.{prop_key}")

        # 7. Final component construction
        full_code = f"""// Auto-generated by Astro Language Compiler
{imports_code}

function {ast.name}(props) {{
  const defaultProps = {json.dumps(ast.props)};
  const finalProps = {{ ...defaultProps, ...props }};

  // --- Reactive States ---
{state_code}
  // --- Scoped Styles ---
{styles_code}  // --- Side Effects ---
{effects_code}  // --- Reactive Methods ---
{methods_code}  // --- JSX Layout ---
  return (
{jsx}
  );
}}

export default {ast.name};
"""
        return full_code